name = "GeoParams"
uuid = "e018b62d-d9de-4a26-8697-af89c310ae38"
authors = ["Boris Kaus <kaus@uni-mainz.de>, Albert De Montserrat <albertdemontserratnavarro@erdw.ethz.ch>"]
version = "0.3.18"

[deps]
BibTeX = "7b0aa2c9-049f-5cec-894a-2b6b781bb25e"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
KernelDensitySJ = "49dc5b4e-6806-4504-b2cc-a81764e7a38b"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Loess = "4345ca2d-374a-55d4-8d30-97f9976e7612"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Setfield = "efcf1570-3423-57d1-acb7-fd33fddbac46"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
UnPack = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
Unidecode = "967fb449-e509-55aa-8007-234b4096b967"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
BibTeX = "0.1"
ForwardDiff = "0.10"
Interpolations = "0.13, 0.14"
KernelDensitySJ = "0.2"
LaTeXStrings = "1.2"
Loess = "0.5"
Parameters = "0.12"
Requires = "0.5.0, 0.6, 0.7, 0.8, 1.0 - 1.3"
Roots = "1.0, 2.0"
Setfield = "0.5.1, 0.6, 0.7, 0.8, 1.0"
StaticArrays = "1.5"
StatsBase = "0.1 - 0.32, 0.33"
UnPack = "1.0"
Unidecode = "1.0"
Unitful = "1.0"
julia = "1.7"

[extras]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
